version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_db
    ports:
      - "54321:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:


# $sudo docker-compose up -d
